TestSystemOnline/TestSystemOnline/Controllers/OperateController.cs
using BLL;
using CommandTools;
using Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestSystemOnline.Controllers
{
    public class OperateController : BaseController
    {
        /// <summary>
        /// 个人基本信息
        /// </summary>
        /// <returns></returns>
        public ActionResult OwnInfo()
        {
            User user = (User)Session["User"];
            DataTable table = null;
            switch (user.RuleName)
            {
                case "学生":
                    StudentBLL student = new StudentBLL();
                    table = student.GetStudent(user.ID);
                    ViewBag.LoginID     = table.Rows[0]["LoginID"].ToString();
                    ViewBag.Sex         = (table.Rows[0]["Sex"].ToString() == "True" ? "男" : "女");
                    ViewBag.Age         = table.Rows[0]["Age"].ToString();
                    ViewBag.RuleName    = table.Rows[0]["RuleName"].ToString();
                    ViewBag.ChangeTime  = Convert.ToDateTime(table.Rows[0]["ChangeTime"]).ToString("yyyy年MM月dd日hh时mm分");
                    ViewBag.ClassName   = table.Rows[0]["ClassName"].ToString();
                    ViewBag.ClassMaster = table.Rows[0]["TeacherName"].ToString();
                    break;
                case "教师":
                    TeacherBLL teacher = new TeacherBLL();
                    table = teacher.GetTeacher(user.ID);
                    ViewBag.LoginID     = table.Rows[0]["LoginID"].ToString();
                    ViewBag.Sex         = (table.Rows[0]["Sex"].ToString() == "True" ? "男" : "女");
                    ViewBag.Age         = table.Rows[0]["Age"].ToString();
                    ViewBag.ChangeTime  = Convert.ToDateTime(table.Rows[0]["ChangeTime"]).ToString("yyyy年MM月dd日hh时mm分");
                    ViewBag.PostName    = table.Rows[0]["PostName"].ToString();
                    ViewBag.ClassMaster = (table.Rows[0]["ClassName"].ToString() == "" ? "不是" : "是");
                    ViewBag.ClassName   = (table.Rows[0]["ClassName"].ToString() == "" ? "不定" : table.Rows[0]["ClassName"].ToString());
                    ViewBag.CourseName  = table.Rows[0]["CourseName"].ToString();
                    break;
                case "管理员":
                    AdminBLL admin = new AdminBLL();
                    table = admin.GetAdmin(user.ID);
                    ViewBag.LoginID    = table.Rows[0]["LoginID"].ToString();
                    ViewBag.Sex        = (table.Rows[0]["Sex"].ToString() == "True" ? "男" : "女");
                    ViewBag.Age        = table.Rows[0]["Age"].ToString();
                    ViewBag.RuleName   = table.Rows[0]["RuleName"].ToString();
                    ViewBag.ChangeTime = Convert.ToDateTime(table.Rows[0]["ChangeTime"]).ToString("yyyy年MM月dd日hh时mm分");
                    break;
                default:
                    break;
            }
            return View();
        }
        /// <summary>
        /// 所有班级信息
        /// </summary>
        /// <param name="pageIndex"></param>
        /// <returns></returns>
        public ActionResult AllClassPage(int pageIndex,string key, string value)
        {
            ViewBag.ClassKey    = key;              //搜索条件
            ViewBag.SearchValue = value;            //搜索的值

            ClassBLL classBLL = new ClassBLL();

            int PageSize   = 4;                                                       //页容量
            int TotalCount = classBLL.GetDataCount(key, value);                       //数据总量
            int TotalPages = (int)Math.Ceiling(TotalCount / (double)PageSize);        //分页张数
            int PageIndex  = pageIndex;                                               //页面索引
                        
            if (PageIndex >= TotalPages)
            {
                PageIndex = TotalPages - 1;
            }
            if (PageIndex < 0)
            {
                PageIndex = 0;
            }
            PagePading(PageSize,TotalCount,TotalPages,PageIndex);// 分页

            DataTable table = classBLL.GetClassQuery(PageIndex, PageSize, key, value);
            return View(table);
        }
        /// <summary>
        /// 查看班级详细信息
        /// </summary>
        /// <param name="guid"></param>
        /// <returns></returns>
        public ActionResult GetClassDetail(Guid guid)
        {
            DataTable table = new ClassBLL().GetClassByID(guid);
            if (table.Rows.Count > 0)
            {
                return Content(new AjaxResult
                {
                    state = ResultType.success.ToString(),
                    data = table
                }.ToJson());
            }
            else
            {
                return Content(new AjaxResult
                {
                    state = ResultType.info.ToString(),
                    data = null,
                    message = "获取详细信息失败！"
                }.ToJson());
            }
        }
        /// <summary>
        /// 所有课程信息
        /// </summary>
        /// <returns></returns>
        public ActionResult AllCoursePage(int pageIndex,string key, string value)
        {
            ViewBag.CourseKey   = key;              //搜索条件
            ViewBag.SearchValue = value;            //搜索的值

            CourseBLL courseBLL = new CourseBLL();

            int PageSize   = 8;                                                        //页容量
            int TotalCount = courseBLL.GetDataCount(key, value);                       //数据总量
            int TotalPages = (int)Math.Ceiling(TotalCount / (double)PageSize);         //分页张数
            int PageIndex  = pageIndex;                                                //页面索引

            if (PageIndex >= TotalPages)
            {
                PageIndex = TotalPages - 1;
            }
            if (PageIndex < 0)
            {
                PageIndex = 0;
            }
            PagePading(PageSize, TotalCount, TotalPages, PageIndex);// 分页

            DataTable table = courseBLL.GetCourseQuery(PageIndex, PageSize, key, value);
            return View(table);

        }
        /// <summary>
        /// 查看课程详细信息
        /// </summary>
        /// <param name="guid"></param>
        /// <returns></returns>
        public ActionResult GetCourseDetail(Guid guid)
        {
            DataTable table = new CourseBLL().GetCourseDetail(guid);
            if (table.Rows.Count > 0)
            {
                return Content(new AjaxResult
                {
                    state = ResultType.success.ToString(),
                    data = table
                }.ToJson());
            }
            else
            {
                return Content(new AjaxResult
                {
                    state = ResultType.info.ToString(),
                    data = null,
                    message = "获取详细信息失败！"
                }.ToJson());
            }
        }
        /// <summary>
        /// 分页按钮
        /// </summary>
        /// <param name="pageIndex">当前页</param>
        /// <param name="table"></param>
        /// <returns></returns>
        private void PagePading(int PageSize,int TotalCount,int TotalPages,int PageIndex)
        {
            if (TotalCount == 0)
            {
                ViewBag.PageIndex  = 0;
                ViewBag.PageSize   = 0;
                ViewBag.TotalCount = 0;
                ViewBag.TotalPages = 1;
            }
            else
            {
                ViewBag.PageIndex  = PageIndex;
                ViewBag.PageSize   = PageSize;
                ViewBag.TotalCount = TotalCount;
                ViewBag.TotalPages = TotalPages;
            }
            
        }
        /// <summary>
        /// 修改个人头像页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePhoto()
        {
            return View();
        }
        /// <summary>
        /// 修改个人头像方法
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ChangePhoto(FormCollection form)
        { 
            // 如果Request.Files.Count 文件数为0上传不成功
            if (Request.Files.Count == 0)
            {
                return View();
            }

            // 文件大小大（以字节为单位）为0时，做一些操作
            var file = Request.Files[0];
            if (file.ContentLength == 0)
            {
                return View();
            }
            else
            {
                file = Request.Files[0];
                string target   = Server.MapPath("\\") + ("Image\\Photo\\");    // 取得目标文件夹的路径
                string filename = file.FileName;                                // 取得文件名字
                string path     = target + filename;                            // 获取存储的目标地址
                file.SaveAs(path);

                StudentBLL student = new StudentBLL();
                User user = (User)Session["User"];

                if (user != null)
                {
                    user.ImgUrl = "/Image/Photo/" + filename;
                    if (CheckUserChange(user))
                    {
                        Session["User"] = user;
                        return RedirectToAction("../Home/" + ViewBag.RuleTemp);
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    Logout();
                }
            }
            return View();
        }
        /// <summary>
        /// 确认用户权限修改头像
        /// </summary>
        /// <param name="img">头像地址</param>
        /// <returns></returns>
        public bool CheckUserChange(User user)
        {
            switch (user.RuleName)
            {
                case "学生":
                    return new StudentBLL().ChangePhoto(user.ID, user.ImgUrl);
                case "教师":
                    return new TeacherBLL().ChangePhoto(user.ID, user.ImgUrl);
                case "管理员":

TestSystemOnline/TestSystemOnline/Views/Operate/AllClassPage.cshtml
@{
    ViewBag.Title = "班级信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data;
@{
    DataTable table = new DataTable();
    table = Model;
}
<div class="operate-box">
    <div class="back-bottom">
        <i class="fa fa-home fa-10x"></i>
    </div>
    <div class="back-top">
        <h1 class="title-operate">
            <i class="fa fa-home"></i>
            所有班级信息
            <span style="font-size: 22px;color: grey;">- All class information</span>
        </h1>
        <div class="content-operate">
            <div class="class-card">
                <div id="class_table">
                    @{
                        if (table != null)
                        {
                            foreach (DataRow item in table.Rows)
                            {
                                <div class="class-temp">
                                    <div class="class-box">
                                        <img id="class_img" src="@(item["ClassImg"].ToString() == "" ? "/Image/Classroom/classtemp.png" : item["ClassImg"])" alt="" />
                                        <div class="class-cover-img"></div>
                                        <div class="class-cover-info">
                                            <div class="class-name">@item["ClassName"]</div>
                                            <div class="class-master">班主任：@item["Name"]</div>
                                            <div class="class-detail" onclick='ClassDetail("@item["ID"]")'>详细</div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
                <div class="paging">
                    <div class="class-search ">
                        <select id="dropClassCountries" name="key">
                            @{
                                if (ViewBag.ClassKey == "ClassName")
                                {
                                    <option value="ClassName" selected="selected">班级名</option>
                                    <option value="Name">班主任</option>
                                }
                                else
                                {
                                    <option value="ClassName">班级名</option>
                                    <option value="Name" selected="selected">班主任</option>
                                }
                            }
                        </select>
                        <input id="txtClassSearch" type="text" name="search" placeholder="请输入关键字" value="@ViewBag.SearchValue" />
                        <button id="btnSearchClassOK" type="button" onclick="ClassQuery()"><span>搜索</span></button>
                    </div>
                    <div class="pading-btn" onclick="GotoPage(@(ViewBag.PageIndex + 1))"><i class="fa fa-angle-right"></i></div>
                    <ul class="paging-ul">
                        @{
                            int totalPages = ViewBag.TotalPages;
                            for (int i = 0; i < totalPages; i++)
                            {
                                string temp = (i + 1).ToString();
                                <li class="pading-li" onclick="GotoPage(@i)">@temp</li>

                            }
                        }
                    </ul>
                    <div class="pading-btn" onclick="GotoPage(@(ViewBag.PageIndex - 1))"><i class="fa fa-angle-left"></i></div>
                    <div class="pading-info">
                        <span id="pading_info">共 @(ViewBag.TotalCount) 条/全 @(ViewBag.TotalPages) 页，当前第 @(ViewBag.PageIndex + 1) 页</span>
                    </div>
                </div>
                <div id="class_show_box" class="class-show-box">
                    <div class="box-content">
                        <div class="box_close" onclick="CloseBox()"><i class="fa fa-times-circle fa-2x"></i></div>
                        <div class="show-box-img">
                            <img id="show_box_img" src="" alt="" />
                        </div>
                        <div class="show-box-info">
                            <div id="show_box_title" class="show-box-title"></div>
                            <div class="box-info-bar">
                                <div class="box-info-left">班主任&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="class_master"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">专业课程&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="class_course"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">班级人数&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="class_number"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">选修课程&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="other_course"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Script/Operate/all-class-page.js"></script>
</div>

TestSystemOnline/TestSystemOnline/Views/Operate/AllCoursePage.cshtml
@{
    ViewBag.Title = "课程信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data;
@{
    DataTable table = new DataTable();
    table = Model;
}
<div class="operate-box">
    <div class="back-bottom">
        <i class="fa fa-book fa-10x"></i>
    </div>
    <div class="back-top">
        <h1 class="title-operate">
            <i class="fa fa-book"></i>
            所有课程信息
            <span style="font-size: 22px;color: grey;">- All course information</span>
        </h1>
        <div class="content-operate">
            <div class="course-card">
                <div id="course_table">
                    @{
                        if (table != null)
                        {
                            foreach (DataRow item in table.Rows)
                            {
                                <div class="course-temp">
                                    <div class="course-box" onclick='CourseDetail("@item["ID"]")'>
                                        <img id="course_img" src="@(item["BookImg"].ToString() == "" ? "/Image/Book/9787111211969.jpg" : item["BookImg"])" alt="" />
                                        <div class="course-cover-img"></div>
                                        <div class="course-cover-info">
                                            <div class="course-name">@(item["CourseName"].ToString().Length > 10 ? item["CourseName"].ToString().Substring(0, 10) + "..." : item["CourseName"])</div>
                                            <div class="course-compulsory">@(item["Compulsory"].ToString() == "True" ? "必修" : "选修")</div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
                <div class="paging">
                    <div class="course-search">
                        <select id="dropCourseCountries" name="key">
                            @{
                                if (ViewBag.CourseKey == "CourseName")
                                {
                                    <option value="CourseName" selected="selected">课程名</option>
                                    <option value="Name">教师名</option>
                                    <option value="Book">教材名</option>
                                }
                                else if (ViewBag.CourseKey == "Name")
                                {
                                    <option value="CourseName">课程名</option>
                                    <option value="Name" selected="selected">教师名</option>
                                    <option value="Book">教材名</option>
                                }
                                else
                                {
                                    <option value="CourseName">课程名</option>
                                    <option value="Name">教师名</option>
                                    <option value="Book" selected="selected">教材名</option>
                                }
                            }
                        </select>
                        <input id="txtCourseSearch" type="text" name="search" placeholder="请输入关键字" value="@ViewBag.SearchValue" />
                        <button id="btnSearchCourseOK" type="button" onclick="CourseQuery()"><span>搜索</span></button>
                    </div>
                    <div class="pading-btn" onclick="GotoPage(@(ViewBag.PageIndex + 1))"><i class="fa fa-angle-right"></i></div>
                    <ul class="paging-ul">
                        @{
                            int totalPages = ViewBag.TotalPages;
                            for (int i = 0; i < totalPages; i++)
                            {
                                string temp = (i + 1).ToString();
                                <li class="pading-li" onclick="GotoPage(@i)">@temp</li>

                            }
                        }
                    </ul>
                    <div class="pading-btn" onclick="GotoPage(@(ViewBag.PageIndex - 1))"><i class="fa fa-angle-left"></i></div>
                    <div class="pading-info">
                        <span id="pading_info">共 @(ViewBag.TotalCount) 条/全 @(ViewBag.TotalPages) 页，当前第 @(ViewBag.PageIndex + 1) 页</span>
                    </div>
                </div>
                <div id="course_show_box" class="course-show-box">
                    <div class="box-content">
                        <div class="box_close" onclick="CloseBox()"><i class="fa fa-times-circle fa-2x"></i></div>
                        <div class="show-box-img">
                            <img id="show_box_img" src="" alt="" />
                        </div>
                        <div class="show-box-info">
                            <div id="show_box_title" class="show-box-title"></div>
                            <div class="box-info-bar">
                                <div class="box-info-left">课本&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="course_book"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">必修&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="course_compulsory"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">教师&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="course_teacher"></div>
                            </div>
                            <div class="box-info-bar">
                                <div class="box-info-left">课程信息&nbsp;:&nbsp;</div>
                                <div class="box-info-right" id="course_message"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Script/Operate/all-course-page.js"></script>
</div>

TestSystemOnline/TestSystemOnline/Views/Operate/ChangePass.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="operate-box">
    <div id="rule_temp" style="display:none;">@ViewBag.RuleTemp</div>
    <div class="back-bottom">
        <i class="fa fa-unlock-alt fa-10x"></i>
    </div>
    <div class="back-top">
        <h1 class="title-operate">
            <i class="fa fa-unlock-alt"></i>
            修改登录密码
            <span style="font-size: 22px;color: grey;">- Modify the login password</span>
        </h1>
        <div class="content-operate">
            <form class="form-card">
                <div class="input-container">
                    <input type="password" id="txtOldPass" required="required" maxlength="10" />
                    <label for="txtOldPass">原始密码</label>
                </div>
                <div class="input-container">
                    <input type="password" id="txtNewPass" required="required" maxlength="10" />
                    <label for="txtNewPass">重设密码</label>
                </div>
                <div class="input-container">
                    <input type="password" id="txtChePass" required="required" maxlength="10" />
                    <label for="txtChePass">确认密码</label>
                </div>
                <div class="button-container">
                    <button id="btnOK" type="button"><span>确认</span></button>
                    <div class="tips">
                        <div class="msg">&nbsp;</div>
                    </div>
                </div>
            </form>
            <script src="~/Script/Operate/change-pass.js"></script>
        </div>
    </div>
</div>

TestSystemOnline/TestSystemOnline/Views/Operate/ChangePhoto.cshtml
@{
    ViewBag.Title = "个人头像";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="operate-box">
    <div class="back-bottom">
        <i class="fa fa-camera fa-10x"></i>
    </div>
    <div class="back-top">
        <h1 class="title-operate">
            <i class="fa fa-camera"></i>
            修改个人头像
            <span style="font-size: 22px;color: grey;">- Amend a personal image</span>
        </h1>
        <div class="content-operate">
            <div class="headimg-card">
                <div class="headimg-top">
                    <img id="img_big" src="@ViewBag.Photo" alt="" />
                    <img id="img_small" src="@ViewBag.Photo" alt="" />
                    <h2>@ViewBag.Name</h2>
                </div>
                <div class="headimg-bottom">
                    @using (Html.BeginForm("ChangePhoto", "Operate", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="headimg-mess">
                            <span>请选择您作为头像图片：</span>
                            <input name="file" type="file" accept=".jpg,.png" id="file_upload" />
                        </div>
                        <div class="headimg-btn">
                            <button id="btnOK" type="submit" disabled="disabled"><span>确认</span></button>
                            <div class="tips">
                                <div class="msg">&nbsp;</div>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
    <script src="~/Script/Operate/change-photo.js"></script>
</div>

TestSystemOnline/TestSystemOnline/Views/Operate/OwnInfo.cshtml
@{
    ViewBag.Title = "个人信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="operate-box">
    <div class="back-bottom">
        <i class="fa fa-user fa-10x"></i>
    </div>
    <div class="back-top">
        <h1 class="title-operate">
            <i class="fa fa-user"></i>
            查看个人信息
            <span style="font-size: 22px;color: grey;">- View personal information</span>
        </h1>
        <div class="content-operate">
            <div class="own-card">
                <div class="own-img">
                    <img id="own_photo" src="@ViewBag.Photo" alt="" />
                    <h2>@ViewBag.Name</h2>
                </div>
                <div class="own-info">
                    <div class="info-bar">
                        <div class="info-bar-lfet">账号&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.LoginID</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">性别&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.Sex</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">年龄&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.Age</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">身份&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.RuleName</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">职位&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.PostName</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">修改时间&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.ChangeTime</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">班级&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.ClassName</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">班主任&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.ClassMaster</div>
                    </div>
                    <div class="info-bar">
                        <div class="info-bar-lfet">专业&nbsp;:&nbsp;</div>
                        <div class="info-bar-right">@ViewBag.CourseName</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Script/Operate/own-info.js"></script>
</div>